# version: "3.8"

# services:
#   postgres:
#     image: postgres:13
#     container_name: postgres_db
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: finance_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   airflow:
#     image: apache/airflow:latest
#     container_name: airflow_scheduler
#     restart: always
#     depends_on:
#       - postgres
#     environment:
#       AIRFLOW__CORE__EXECUTOR: LocalExecutor
#       AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/finance_db
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./airflow/dags:/opt/airflow/dags
#       - ./airflow/logs:/opt/airflow/logs
#       - ./airflow/plugins:/opt/airflow/plugins
#     command: ["airflow", "scheduler"]

#   streamlit:
#     build: ./streamlit_app
#     container_name: streamlit_dashboard
#     restart: always
#     depends_on:
#       - postgres
#     ports:
#       - "8501:8501"
#     environment:
#       #DB_HOST: postgres
#       DB_HOST: postgres
#       DB_USER: postgres
#       DB_PASSWORD: postgres
#       DB_NAME: finance_db

# volumes:
#   postgres_data:
version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build: .
    container_name: airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finance_db
    volumes:
      - .:/opt/airflow
      - airflow_logs:/opt/airflow/logs
    ports:
      - "8080:8080"

  streamlit:
    build: ./streamlit_app
    container_name: streamlit_app
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION=postgresql://postgres:postgres@postgres:5432/finance_db
    ports:
      - "8501:8501"

volumes:
  postgres_data:
  airflow_logs:
