version: "3.8"

services:
  streamlit:
    build: ./streamlit_app
    container_name: streamlit_dashboard
    restart: always
    ports:
      - "8501:8501"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: finance_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - astro_network

networks:
  astro_network:
    external: true
    name: end-to-end-etl_143e2a_airflow  # This is your actual Astro network
